using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Diagnostics;
using Microsoft.CodeAnalysis.Text;

using static NEM.ScriptCodeGen.ScriptManifestRules;
using static NEM.ScriptCodeGen.ScriptIdentity;

namespace NEM.ScriptCodeGen
{
    internal static class ScriptManifestEmitter
    {
        internal static void Emit(SourceProductionContext spc, ImmutableArray<ScriptTypeModel?> items,
            ImmutableArray<string> metaContents, bool validateOnly)
        {
            var models = items.Where(m => m != null).Select(m => m!).ToList();
            ScriptMetaIndex? meta = ScriptMetaIndex.Read(spc, metaContents);
            if (meta == null) { return; }

            // ID 解決の優先順: 明示属性 → sidecar metadata → 決定的 fallback。
            foreach (ScriptTypeModel model in models)
            {
                bool hasStable;
                if (model.HasExplicitID && !model.InvalidID)
                {
                    // model.NormalizedID は attribute 由来で確定済み
                    hasStable = true;
                }
                else if (meta.TryGetScriptID(model.FullTypeName, out string metaID) &&
                    TryNormalizeGuid(metaID, out string normalizedMeta))
                {
                    model.NormalizedID = normalizedMeta;
                    hasStable = true;
                }
                else
                {
                    // metadata も attribute も無い（CI で sync 未実行など）。決定的 fallback
                    hasStable = false;
                }
                model.HasStableID = hasStable;
            }

            // 診断: 不正 attribute / stable id 欠落 / 重複
            foreach (ScriptTypeModel model in models)
            {
                if (model.HasExplicitID && model.InvalidID)
                {
                    spc.ReportDiagnostic(Diagnostic.Create(InvalidIDRule, model.Location, model.FullTypeName, model.RawID));
                }
                else if (!model.HasStableID)
                {
                    spc.ReportDiagnostic(Diagnostic.Create(
                        validateOnly ? MissingIDValidateRule : MissingIDRule, model.Location, model.FullTypeName));
                }
            }

            var seen = new Dictionary<string, ScriptTypeModel>(StringComparer.Ordinal);
            foreach (ScriptTypeModel model in models)
            {
                if (seen.TryGetValue(model.NormalizedID, out ScriptTypeModel? other))
                {
                    spc.ReportDiagnostic(Diagnostic.Create(DuplicateIDRule, model.Location,
                        model.FullTypeName, other.FullTypeName, model.NormalizedID));
                }
                else
                {
                    seen[model.NormalizedID] = model;
                }
            }

            var builder = new StringBuilder();
            builder.AppendLine("// <auto-generated/>");
            builder.AppendLine("#nullable enable");
            builder.AppendLine("namespace NEMEngine");
            builder.AppendLine("{");
            builder.AppendLine("    internal static class GeneratedScriptManifest");
            builder.AppendLine("    {");
            builder.AppendLine("        public static global::NEMEngine.ScriptTypeDescriptor[] GetDescriptors()");
            builder.AppendLine("        {");
            builder.AppendLine("            return new global::NEMEngine.ScriptTypeDescriptor[]");
            builder.AppendLine("            {");
            foreach (ScriptTypeModel model in models.OrderBy(m => m.FullTypeName, StringComparer.Ordinal))
            {
                builder.Append("                new global::NEMEngine.ScriptTypeDescriptor(");
                builder.Append(EscapeString(model.NormalizedID)).Append(", ");
                builder.Append(EscapeString(model.FullTypeName)).Append(", ");
                builder.Append(EscapeString(model.DisplayName)).Append(", ");
                builder.Append(EscapeString(model.SourcePath)).Append(", ");
                builder.Append(model.HasStableID ? "true" : "false");
                builder.AppendLine("),");
            }
            builder.AppendLine("            };");
            builder.AppendLine("        }");
            builder.AppendLine("    }");
            builder.AppendLine("}");

            spc.AddSource("GeneratedScriptManifest.g.cs", SourceText.From(builder.ToString(), Encoding.UTF8));
        }

        internal static string EscapeString(string value)
        {
            return "\"" + value.Replace("\\", "\\\\").Replace("\"", "\\\"") + "\"";
        }
    }
}
