using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Diagnostics;
using Microsoft.CodeAnalysis.Text;

using static NEM.ScriptCodeGen.ScriptSchemaRules;
using static NEM.ScriptCodeGen.ScriptSchemaAnalysis;
using static NEM.ScriptCodeGen.ScriptFieldAttributes;
using static NEM.ScriptCodeGen.ScriptKindResolver;
using static NEM.ScriptCodeGen.ScriptIdentity;
using static NEM.ScriptCodeGen.ScriptSchemaText;

namespace NEM.ScriptCodeGen
{
    // スクリプト生成のスキーマ出力
    internal static class ScriptSchemaEmitter
    {
        internal static void Emit(SourceProductionContext spc, ImmutableArray<TypeSchema?> items,
            ImmutableArray<string> metaContents, bool validateOnly)
        {
            var schemas = items.Where(s => s != null).Select(s => s!).ToList();
            ScriptMetaIndex meta = ScriptMetaIndex.Build(metaContents);

            ScriptSchemaIdentity.Resolve(spc, schemas, meta, validateOnly);

            // 決定的な JSON を組み立てる（script は GUID、field も GUID で安定ソート）
            var json = new StringBuilder();
            json.Append('{');
            json.Append("\"schemaVersion\":").Append(SchemaVersion).Append(',');
            json.Append("\"scripts\":[");
            bool firstType = true;
            foreach (TypeSchema type in schemas.OrderBy(s => s.ScriptTypeID, StringComparer.Ordinal))
            {
                if (!firstType) json.Append(',');
                firstType = false;
                json.Append('{');
                json.Append("\"scriptTypeId\":").Append(JsonString(type.ScriptTypeID)).Append(',');
                json.Append("\"fullTypeName\":").Append(JsonString(type.FullTypeName)).Append(',');
                json.Append("\"fields\":[");
                bool firstField = true;
                // Inspector 表示はソース宣言順にする（base→derived、宣言順）。
                // 宣言順は syntax 由来で決定的なので artifact の再現性も保たれる（reflection 列挙順には依存しない）。
                foreach (FieldSchema field in type.Fields)
                {
                    if (!firstField) json.Append(',');
                    firstField = false;
                    EmitField(json, field);
                }
                json.Append("]}");
            }
            json.Append("]}");

            var builder = new StringBuilder();
            builder.AppendLine("// <auto-generated/>");
            builder.AppendLine("#nullable enable");
            builder.AppendLine("namespace NEMEngine");
            builder.AppendLine("{");
            builder.AppendLine("    internal static class GeneratedScriptSchema");
            builder.AppendLine("    {");
            builder.Append("        public const string Json = ");
            builder.Append(VerbatimLiteral(json.ToString()));
            builder.AppendLine(";");
            builder.AppendLine("        public static string GetSchemaJson() { return Json; }");
            builder.AppendLine("    }");
            builder.AppendLine("}");

            spc.AddSource("GeneratedScriptSchema.g.cs", SourceText.From(builder.ToString(), Encoding.UTF8));
        }

        internal static void EmitField(StringBuilder json, FieldSchema field)
        {
            json.Append('{');
            json.Append("\"fieldId\":").Append(JsonString(field.FieldID)).Append(',');
            json.Append("\"name\":").Append(JsonString(field.Name)).Append(',');
            json.Append("\"declaringType\":").Append(JsonString(field.DeclaringType)).Append(',');
            json.Append("\"isPublic\":").Append(field.IsPublic ? "true" : "false").Append(',');
            json.Append("\"isReadOnly\":").Append(field.IsReadOnly ? "true" : "false").Append(',');
            json.Append("\"isHidden\":").Append(field.IsHidden ? "true" : "false").Append(',');
            json.Append("\"multiline\":").Append(field.Multiline ? "true" : "false");
            if (field.HasRange)
            {
                json.Append(",\"range\":{\"min\":").Append(FloatLiteral(field.RangeMin))
                    .Append(",\"max\":").Append(FloatLiteral(field.RangeMax)).Append('}');
            }
            if (field.HasMin)
            {
                json.Append(",\"min\":").Append(FloatLiteral(field.MinValue));
            }
            if (field.HasDragSpeed)
            {
                json.Append(",\"dragSpeed\":").Append(FloatLiteral(field.DragSpeed));
            }
            if (field.Tooltip != null)
            {
                json.Append(",\"tooltip\":").Append(JsonString(field.Tooltip));
            }
            if (field.Header != null)
            {
                json.Append(",\"header\":").Append(JsonString(field.Header));
            }
            if (field.Label != null)
            {
                json.Append(",\"label\":").Append(JsonString(field.Label));
            }
            json.Append(',');
            EmitKind(json, field.Kind);
            json.Append('}');
        }

        internal static void EmitKind(StringBuilder json, KindInfo kind)
        {
            json.Append("\"kind\":").Append(JsonString(kind.Kind));
            if (kind.EnumUnderlying != null)
            {
                json.Append(",\"enumUnderlying\":").Append(JsonString(kind.EnumUnderlying));
                json.Append(",\"enumNames\":[");
                for (int i = 0; i < kind.EnumNames.Count; ++i)
                {
                    if (i > 0) json.Append(',');
                    json.Append(JsonString(kind.EnumNames[i]));
                }
                json.Append("],\"enumValues\":[");
                for (int i = 0; i < kind.EnumValues.Count; ++i)
                {
                    if (i > 0) json.Append(',');
                    json.Append(JsonString(kind.EnumValues[i]));
                }
                json.Append(']');
            }
            if (kind.AssetType != null)
            {
                json.Append(",\"assetType\":").Append(JsonString(kind.AssetType));
            }
            if (kind.ScriptType != null)
            {
                json.Append(",\"scriptType\":").Append(JsonString(kind.ScriptType));
            }
            if (kind.ComponentType != null)
            {
                json.Append(",\"componentType\":").Append(JsonString(kind.ComponentType));
            }
            if (kind.ObjectType != null)
            {
                json.Append(",\"objectType\":").Append(JsonString(kind.ObjectType));
            }
            if (kind.Members.Count > 0)
            {
                json.Append(",\"members\":[");
                for (int i = 0; i < kind.Members.Count; ++i)
                {
                    if (i > 0) json.Append(',');
                    EmitField(json, kind.Members[i]);
                }
                json.Append(']');
            }
            if (kind.Candidates.Count > 0)
            {
                json.Append(",\"candidates\":[");
                for (int i = 0; i < kind.Candidates.Count; ++i)
                {
                    if (i > 0) json.Append(',');
                    KindInfo candidate = kind.Candidates[i];
                    json.Append("{\"type\":").Append(JsonString(candidate.ObjectType ?? string.Empty));
                    if (candidate.Members.Count > 0)
                    {
                        json.Append(",\"members\":[");
                        for (int m = 0; m < candidate.Members.Count; ++m)
                        {
                            if (m > 0) json.Append(',');
                            EmitField(json, candidate.Members[m]);
                        }
                        json.Append(']');
                    }
                    json.Append('}');
                }
                json.Append(']');
            }
            if (kind.Element != null)
            {
                json.Append(",\"element\":{");
                EmitKind(json, kind.Element);
                json.Append('}');
            }
        }
    }
}
